version: "3.8"

services:
    db:
        container_name: postgres-container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: goparty_manage
            POSTGRES_PASSWORD: goparty_dbs
            POSTGRES_DB: goparty_db
        ports:
            - "5432:5432"
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
